=== Evgeniy-Menko/16_java_ST2019/WebParsing/src/main/resources/data/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.candies.org" xmlns:tns="http://www.candies.org"
            elementFormDefault="qualified">

    <!-- Element -->
    <xsd:element name="candies">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="candy" maxOccurs="unbounded"
                             minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="tns:String"/>
                            <xsd:element name="energy" type="tns:Energy"/>
                            <xsd:element name="type" type="tns:type"/>
                            <xsd:element name="production" type="tns:String"/>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:unsignedInt" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="unique-id">
            <xsd:selector xpath="tns:candy"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
    </xsd:element>

    <!-- Type -->
    <xsd:complexType name="Ingredients">
        <xsd:sequence>
            <xsd:element name="water" type="tns:Ingredient"/>
            <xsd:element name="sugar" type="tns:Ingredient"/>
            <xsd:element name="fructose" type="tns:Ingredient"/>
            <xsd:element name="vanillin" type="tns:Ingredient"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Value">
        <xsd:sequence>
            <xsd:element name="proteins" type="tns:typeValue"/>
            <xsd:element name="fats" type="tns:typeValue"/>
            <xsd:element name="carbohydrates" type="tns:typeValue"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="type" abstract="true">
        <xsd:attribute name="filling" type="xsd:boolean"
                       default="false"/>
    </xsd:complexType>

    <xsd:complexType name="caramel">
        <xsd:complexContent>
            <xsd:extension base="tns:type">
                <xsd:sequence>
                    <xsd:element name="ingredients" type="tns:Ingredients"/>
                    <xsd:element name="value" type="tns:Value"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="iris">
        <xsd:complexContent>
            <xsd:extension base="tns:type">
                <xsd:sequence>
                    <xsd:element name="ingredients" type="tns:Ingredients"/>
                    <xsd:element name="value" type="tns:Value"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:complexType name="chocolate">
        <xsd:complexContent>
            <xsd:extension base="tns:type">
                <xsd:sequence>
                    <xsd:element name="ingredients">
                        <xsd:complexType>
                            <xsd:complexContent>
                                <xsd:extension base="tns:Ingredients">
                                    <xsd:sequence>
                                        <xsd:element name="chocolateType" type="tns:String"/>
                                    </xsd:sequence>
                                </xsd:extension>
                            </xsd:complexContent>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="value" type="tns:Value"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:complexType name="Energy">
        <xsd:simpleContent>
            <xsd:extension base="tns:unsDecimal">
                <xsd:attribute name="ci" type="tns:Ci" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="Ingredient">
        <xsd:simpleContent>
            <xsd:extension base="tns:unsDecimal">
                <xsd:attribute name="ci" type="tns:Ci" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>


    <xsd:complexType name="typeValue">
        <xsd:simpleContent>
            <xsd:extension base="tns:unsDecimal">
                <xsd:attribute name="ci" type="tns:Ci" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>


    <!-- My Type -->
    <xsd:simpleType name="String">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="2"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Ci">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z]*"/>
            <xsd:minLength value="2"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="unsDecimal">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="0.0"/>
            <xsd:maxExclusive value="50"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== Evgeniy-Menko/16_java_ST2019/WebParsing/src/main/resources/data/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.candies.org"
         xsi:schemaLocation="http://www.candies.org candies.xsd">

    <candy id="1">
        <name>Джек</name>
        <energy ci="cs">49</energy>
        <type filling="true" xsi:type="chocolate">
            <ingredients>
                <water ci="sd">5</water>
                <sugar ci="we">5</sugar>
                <fructose ci="as">6</fructose>
                <vanillin ci="as">6</vanillin>
                <chocolateType>пористый шоколад
                </chocolateType>
            </ingredients>
            <value>
                <proteins ci="as">6</proteins>
                <fats ci="ds">7</fats>
                <carbohydrates ci="sd">7</carbohydrates>
            </value>
        </type>
        <production>КОНТИ</production>
    </candy>

    <candy id="3">
        <name>asd</name>
        <energy ci="sd">49</energy>
        <type filling="false" xsi:type="caramel">
            <ingredients>
                <water ci="sd">7</water>
                <sugar ci="sd">2</sugar>
                <fructose ci="ll">3</fructose>
                <vanillin ci="sd">5</vanillin>
            </ingredients>
            <value>
                <proteins ci="sd">23</proteins>
                <fats ci="sd">23</fats>
                <carbohydrates ci="sd">23</carbohydrates>
            </value>
        </type>
        <production>asd</production>
    </candy>

</candies>
