=== Evgeniy-Menko/16_java_ST2019/Task_4_WebParsing/src/test/resources/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.candies.org" xmlns:tns="http://www.candies.org"
            elementFormDefault="qualified">


    <xsd:element name="candies">
        <xsd:complexType>
            <xsd:sequence>


                <xsd:element name="candy" maxOccurs="unbounded"
                             minOccurs="16">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="tns:String"/>
                            <xsd:element name="energy" type="tns:Energy"/>
                            <xsd:element name="type" type="tns:type"/>
                            <xsd:element name="production" type="tns:String"/>
                            <xsd:element name="productionDate" type="xsd:date"/>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:unsignedInt" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="unique-id">
            <xsd:selector xpath="tns:candy"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
    </xsd:element>


    <xsd:complexType name="Ingredients">
        <xsd:sequence>
            <xsd:element name="water" type="tns:Ingredient"/>
            <xsd:element name="sugar" type="tns:Ingredient"/>
            <xsd:element name="fructose" type="tns:Ingredient"/>
            <xsd:element name="vanillin" type="tns:Ingredient"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Value">
        <xsd:sequence>
            <xsd:element name="proteins" type="tns:typeValue"/>
            <xsd:element name="fats" type="tns:typeValue"/>
            <xsd:element name="carbohydrates" type="tns:typeValue"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="type" abstract="true">
        <xsd:attribute name="filling" type="xsd:boolean"
                       default="false"/>
    </xsd:complexType>

    <xsd:complexType name="caramel">
        <xsd:complexContent>
            <xsd:extension base="tns:type">
                <xsd:sequence>
                    <xsd:element name="ingredients">
                        <xsd:complexType>
                            <xsd:complexContent>
                                <xsd:extension base="tns:Ingredients">
                                    <xsd:sequence>
                                        <xsd:element name="taste" type="tns:typeTaste"
                                                     default="lemon"/>
                                    </xsd:sequence>
                                </xsd:extension>
                            </xsd:complexContent>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="value" type="tns:Value"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="iris">
        <xsd:complexContent>
            <xsd:extension base="tns:type">
                <xsd:sequence>
                    <xsd:element name="ingredients" type="tns:Ingredients"/>
                    <xsd:element name="value" type="tns:Value"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:complexType name="chocolate">
        <xsd:complexContent>
            <xsd:extension base="tns:type">
                <xsd:sequence>
                    <xsd:element name="ingredients">
                        <xsd:complexType>
                            <xsd:complexContent>
                                <xsd:extension base="tns:Ingredients">
                                    <xsd:sequence>
                                        <xsd:element name="chocolateType" type="tns:typeChocolate"
                                                     default="milk chocolate"/>
                                    </xsd:sequence>
                                </xsd:extension>
                            </xsd:complexContent>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="value" type="tns:Value"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:complexType name="Energy">
        <xsd:simpleContent>
            <xsd:extension base="tns:unsDecimal">
                <xsd:attribute name="ci" type="xsd:string" use="required" fixed="kcal"/>

            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="Ingredient">
        <xsd:simpleContent>
            <xsd:extension base="tns:unsDecimal">
                <xsd:attribute name="ci" type="xsd:string" use="required" fixed="mg"/>

            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>


    <xsd:complexType name="typeValue">
        <xsd:simpleContent>
            <xsd:extension base="tns:unsDecimal">
                <xsd:attribute name="ci" type="xsd:string" use="required" fixed="gm"/>

            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>


    <xsd:simpleType name="String">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="2"/>
            <xsd:pattern value="[A-Za-z\W]*[^\d]"/>
        </xsd:restriction>
    </xsd:simpleType>


    <xsd:simpleType name="unsDecimal">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="0.0"/>
            <xsd:maxExclusive value="600"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="typeChocolate">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="milk chocolate"/>
            <xsd:enumeration value="dark chocolate"/>
            <xsd:enumeration value="porous chocolate"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="typeTaste">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="apple"/>
            <xsd:enumeration value="lemon"/>
            <xsd:enumeration value="pineapple"/>
            <xsd:enumeration value="orange"/>
        </xsd:restriction>
    </xsd:simpleType>


</xsd:schema>

=== Evgeniy-Menko/16_java_ST2019/Task_4_WebParsing/src/main/resources/data/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.candies.org"
         xsi:schemaLocation="http://www.candies.org candies.xsd">

    <candy id="1">
        <name>Alenka</name>
        <energy ci="kcal">49</energy>
        <type filling="true" xsi:type="chocolate">
            <ingredients>
                <water ci="mg">5</water>
                <sugar ci="mg">5</sugar>
                <fructose ci="mg">6</fructose>
                <vanillin ci="mg">6</vanillin>
                <chocolateType>milk chocolate</chocolateType>
            </ingredients>
            <value>
                <proteins ci="gm">6</proteins>
                <fats ci="gm">7</fats>
                <carbohydrates ci="gm">7</carbohydrates>
            </value>
        </type>
        <production>Baranovichi</production>
    </candy>

  <candy id="2">
         <name>Ledenec</name>
         <energy>243</energy>
         <type filling="false" xsi:type="caramel">
             <ingredients>
                 <water>0.2</water>
                 <sugar>15</sugar>
                 <fructose>10</fructose>
                 <vanillin>3.2</vanillin>
                 <taste>orange</taste>
             </ingredients>
             <value>
                 <proteins>0.3</proteins>
                 <fats>0.5</fats>
                 <carbohydrates>11</carbohydrates>
             </value>
         </type>
         <production>Minsk,Belarus</production>
     </candy>

     <candy id="3">
         <name>GoldKey</name>
         <energy>45</energy>
         <type filling="false" xsi:type="iris">
             <ingredients>
                 <water>10</water>
                 <sugar>16</sugar>
                 <fructose>12</fructose>
                 <vanillin>6</vanillin>
             </ingredients>
             <value>
                 <proteins>4</proteins>
                 <fats>14</fats>
                 <carbohydrates>9</carbohydrates>
             </value>
         </type>
         <production/>
     </candy>

     <candy id="4">
         <name>Stolichnay</name>
         <energy>368</energy>
         <type filling="true" xsi:type="chocolate">
             <ingredients>
                 <water>0.1</water>
                 <sugar>15</sugar>
                 <fructose>10</fructose>
                 <vanillin>5</vanillin>
                 <chocolateType>dark chocolate</chocolateType>
             </ingredients>
             <value>
                 <proteins>0.6</proteins>
                 <fats>1.3</fats>
                 <carbohydrates>92.3</carbohydrates>
             </value>
         </type>
         <production>Kommunarka</production>
     </candy>

     <candy id="5">
         <name>MIND-BLOWING LOLLIPOP</name>
         <energy>369</energy>
         <type filling="false" xsi:type="caramel">
             <ingredients>
                 <water>0.1</water>
                 <sugar>15</sugar>
                 <fructose>10</fructose>
                 <vanillin>5</vanillin>
                <taste>lemon</taste>
             </ingredients>
             <value>
                 <proteins>0.6</proteins>
                 <fats>1.3</fats>
                 <carbohydrates>96.3</carbohydrates>
             </value>
         </type>
         <production>Kommunarka</production>
     </candy>

     <candy id="6">
         <name>Apple</name>
         <energy>357</energy>
         <type filling="false" xsi:type="caramel">
             <ingredients>
                 <water>0.1</water>
                 <sugar>15</sugar>
                 <fructose>10</fructose>
                 <vanillin>5</vanillin>
                 <taste>apple</taste>
             </ingredients>
             <value>
                 <proteins>0.1</proteins>
                 <fats>0.1</fats>
                 <carbohydrates>92.7</carbohydrates>
             </value>
         </type>
         <production>Spartak</production>
     </candy>

</candies>
